name: mentor

version: '3.9'

services:
  db:
    container_name: mentor_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mentor
      POSTGRES_PASSWORD: mentor
      POSTGRES_DB: mentor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: mentor_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: mentor_ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   entrypoint: >
  #     bash -c "
  #       ollama serve &
  #       sleep 3 &&
  #       ollama pull mistral &&
  #       tail -f /dev/null
  #     "

  # api:
  #   container_name: mentor_api
  #   build:
  #     context: ../../
  #   command: poetry run python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis
      # networks:
      # - mentor_network

  # celery:
  #   container_name: mentor_celery
  #   build:
  #     context: ../../
  #   command: poetry run celery -A mentor worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - api

# networks:
#   mentor_network:

volumes:
  db_data:
  redis_data:
  # ollama_data:
