name: mentor

version: '3.9'

services:
  db:
    container_name: mentor_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mentor}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mentor}
      POSTGRES_DB: ${POSTGRES_DB:-mentor}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: mentor_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    container_name: mentor_api
    build:
      context: ../
    command: ./entrypoint.sh
    environment:
      PG_USERNAME: ${PG_USERNAME:-mentor}
      PG_PASSWORD: ${PG_PASSWORD:-mentor}
      PG_DB_NAME: ${PG_DB_NAME:-mentor}
      PG_PORT: ${PG_PORT:-5432}
      PG_HOST: db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    container_name: mentor_celery
    build:
      context: ../
    command: poetry run celery -A mentor.core worker --loglevel=info
    environment:
      PG_PASSWORD: ${PG_PASSWORD:-mentor}
      PG_HOST: db
      REDIS_URL: redis://redis:6379/0
      API_KEY: ${API_KEY?Please set the API_KEY environment variable}
    depends_on:
      - redis
      - api

volumes:
  db_data:
  redis_data:
