# Generated by Django 5.2.4 on 2025-07-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='session_id',
            new_name='session',
        ),
    ]
