# Generated by Django 5.2.4 on 2026-07-24 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_add_created_at_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="language",
            field=models.CharField(
                blank=True,
                default="pt",
                help_text="Language of the session.",
                max_length=2,
            ),
        ),
    ]
